# Generated by Django 5.0.2 on 2024-02-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slag', models.SlugField(max_length=250)),
                ('content', models.TextField()),
                ('price', models.FloatField()),
                ('published_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, max_length=2)),
            ],
        ),
    ]
