# Generated by Django 5.0.2 on 2024-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrepetitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='status',
            field=models.CharField(choices=[('DF', 'Черновик'), ('PF', 'Опубликовано')], default='DF', max_length=2),
        ),
    ]
