# Generated by Django 5.0.2 on 2024-03-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrepetitor', '0003_rubric_bd_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='slag',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
